### ISSUE TITLE
add option to install jupyterlab desktop in index.html

### ISSUE THREAD

**Issue by jt14den** [chennesy/lc-python-intro#21]
jupyterlab desktop is the easiest one-step way to get started in python + jupyter <https://github.com/jupyterlab/jupyterlab-desktop>

**Comment by chennesy** [comment]
Thanks @jt14den! Should we replace the Anaconda instructions with new ones for Jupyterlab Desktop? I'd rather choose one or the other since folks who are brand new would likely be confused by the options. It could also create troubleshooting challenges for instructors who would need to support both Anaconda and JupyterLab Desktop.
