### ISSUE TITLE
Carpentries style guide

### ISSUE THREAD

**Issue by jt14den** [chennesy/lc-python-intro#80]
I forget about the style guide <https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html>. Note @scottcpeterson there's guidance for 'data frame' usage in there.

**Comment by chennesy** [comment]
Thanks @jt14den! I'll do a full pass through the lesson with eyes on the style guide once we've resolved the major content issues. Others can feel free to use the style guide as they're making other content changes, but let's avoid doing a bunch of small PRs to address single items from the style guide right now (e.g., don't do a PR just to update "dataframe" to "DataFrame" in a single episode). Otherwise, managing the PR approval/review/conflict process will get unruly.

**Comment by jt14den** [comment]
Thanks @chennesy, will hold off on copyediting.
